name: CD deploy main
on:
  push:
    branches:
      - main
jobs:
  deploy-main:
    env:
      HAS_INFRA_TOKEN: ${{ secrets.TWENTY_INFRA_TOKEN }}
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        if: ${{ env.HAS_INFRA_TOKEN != '' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TWENTY_INFRA_TOKEN }}
          repository: twentyhq/twenty-infra
          event-type: auto-deploy-main
          client-payload: '{"github": ${{ toJson(github) }}}' # Passes the entire github context to the downstream workflow
